### ISSUE TITLE
เพิ่มหน้า admin.users.show แสดงหน้าจอข้อมูล user id ที่ระบุ

### ISSUE THREAD

**Issue by xemoe** [xemoe/laravel8-coreui-admin-template#1]
### TODO

- [x]  เพิ่มการทดสอบหน้า admin.users.show
- [x]  เพิ่ม Route admin.users.show
- [x]  เพิ่ม UsersController@show(User $user)
- [x]  เพิ่ม Views domain.admin.users.show

**Comment by xemoe** [comment]
### Done
- [x] 8da0477f7f8ddb8b8c859656319ccbdaf7490af7

**Comment by xemoe** [comment]
### TODO
- [ ] create PR to main branch
