### ISSUE TITLE
เพิ่มหน้า admin.users.destroy แสดงแบบฟอร์มลบ user id ที่ระบุ

### ISSUE THREAD

**Issue by xemoe** [xemoe/laravel8-coreui-admin-template#3]
### TODO

- [x]  เพิ่มการทดสอบหน้า admin.users.{destroy}
- [x]  เพิ่ม Route admin.users.{destroy}
- [x]  เพิ่ม UsersController@destroy(User $user)

**Comment by xemoe** [comment]
### Done
- [x] 47bf259953c275970991ad547f3ff7f036375395
